CREATE TABLE IF NOT EXISTS faqs (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  category_ar VARCHAR(150) NOT NULL,
  category_en VARCHAR(150) NULL,
  question_ar VARCHAR(500) NOT NULL,
  question_en VARCHAR(500) NULL,
  answer_ar TEXT NOT NULL,
  answer_en TEXT NULL,
  display_order INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_faqs_active_order (active, display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO faqs (id, category_ar, category_en, question_ar, question_en, answer_ar, answer_en, display_order, active) VALUES
(1, 'الشبكة التجارية', 'Trade network',
 'هل لازم أنضم للشبكة التجارية؟', 'Do I have to join the trade network?',
 'لا، الانضمام للشبكة اختياري تمامًا. تقدر تستخدم Partiva لإدارة نشاطك فقط بدون الانضمام لأي شبكة.',
 'No. Joining the network is completely optional. You can use Partiva to manage your business without joining any network.',
 1, TRUE),
(2, 'الخصوصية والبيانات', 'Privacy & data',
 'بيانات نشاطي هتبقى منفصلة عن التجار التانيين؟', 'Will my business data be separate from other traders?',
 'أيوه، كل نشاط تجاري ليه بياناته الخاصة، ومفيش أي نشاط تاني يقدر يشوفها إلا لو انت فعّلت مشاركتها عبر الشبكة الاختيارية.',
 'Yes. Every business has its own data, and no other business can see it unless you enable sharing through the optional network.',
 2, TRUE),
(3, 'التسجيل والمراجعة', 'Registration & review',
 'بيحصل إيه بعد ما أسجل؟', 'What happens after I register?',
 'طلبك بيدخل في مراجعة قبل التفعيل، وهتوصلك رسالة على الإيميل بقرار الطلب — القبول أو الرفض.',
 'Your request is reviewed before activation, and you will receive an email with the decision — approval or rejection.',
 3, TRUE),
(4, 'التسجيل والمراجعة', 'Registration & review',
 'هل التفعيل بيكون فوري؟', 'Is activation immediate?',
 'لا، التسجيل يخضع للمراجعة أولًا ولا يمنح دخولًا فوريًا.',
 'No. Registration is reviewed first and does not grant immediate access.',
 4, TRUE),
(5, 'الأسعار والخطط', 'Pricing & plans',
 'أقدر أغيّر خطتي بعد التسجيل؟', 'Can I change my plan after registration?',
 'أيوه، تقدر تغيّر خطتك في أي وقت.', 'Yes, you can change your plan at any time.',
 5, TRUE),
(6, 'الأسعار والخطط', 'Pricing & plans',
 'بيحصل إيه لو تعديت حدود خطتي؟', 'What happens if I exceed my plan limits?',
 'الحدود بتتطبّق فورًا مع أي تغيير في الخطة.', 'Limits are applied immediately whenever the plan changes.',
 6, TRUE);
